FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    openssh-client sshpass git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir ansible ansible-lint

WORKDIR /ansible

ENTRYPOINT [ "ansible-playbook" ]
