- name: Main_Server | Minecraft Pipeline
  hosts: main_server
  become: true
  gather_facts: true

  vars:
    node_exporter_version: "1.12.1"
    node_exporter_port: 9100
    ipmi_exporter_port: 9290

  tasks:
    #--------------------------------------------------------
    # Phase 1: JAVA-Check + Installation for NeoForge
    #--------------------------------------------------------
    - name: Check Java installation
      command: java -version
      register: java_check
      ignore_errors: true
      changed_when: false
      check_mode: false

    - name: Install Java 21, if not present
      apt:
        name: openjdk-21-jre-headless
        state: present
        update_cache: true
      when: java_check.rc != 0

    - name: Installed Java-versions
      command: java -version
      register: java_final
      changed_when: false
      check_mode: false

    - name: Java-Version Check
      debug:
        msg: "Java is already installed. Version: {{ java_final.stderr_lines[0] }}"
      when: java_check.rc == 0

    #--------------------------------------------------------
    # Phase 2: Install Node Exporter
    #--------------------------------------------------------
    - name: node_exporter | Download and unzip Node Exporter binary
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp
        remote_src: true
    
    - name: node_exporter Binary an richtige Stelle kopieren
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: /usr/local/bin/node_exporter
        mode: '0755'                 # rwxr-xr-x - ausführbar für alle, schreibbar nur für root
        remote_src: true
    
    - name: systemd-Service-File | Create for Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=nobody
          ExecStart=/usr/local/bin/node_exporter --web.listen-address=:{{ node_exporter_port }}
          Restart=always

          [Install]
          WantedBy=multi-user.target
        notify: node_exporter | Reload systemd

    - name: node_exporter | Activate and start Node Exporter service
      systemd:
        name: node_exporter
        enabled: true
        state: started
        daemon_reload: true
    

    #--------------------------------------------------------
    # Phase 3: Install IPMI Exporter
    #--------------------------------------------------------
    - name: ipmitool install | Download and install IPMI tool
      apt:
        name: ipmitool
        state: present
    
    - name: IPMI Kernel | Load IPMI kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - ipmi_devintf
        - ipmi_si
    
  handlers:
    - name: node_exporter | Reload systemd
      systemd:
        name: node_exporter
        state: restarted