---
- name: Deploy Prometheus Exporter
  hosts: TobisServer
  become: true
  roles:
    - node_exporter
    - smartctl_exporter
    - ipmi_exporter

- name: Deploy Java
  hosts: TobisServer
  become: true
  roles:
    - java

- name: Deploy Minecraft Server
  hosts: TobisServer
  become: true
  roles:
    - minecraft
