---
- name: Deploy Prometheus Exporter
  hosts: TobisServer
  become: true
  roles:
    - prometheus_exporter

- name: Deploy Java
  hosts: TobisServer
  become: true
  roles:
    - java

- name: Deploy Minecraft Server
  hosts: TobisServer
  become: true
  roles:
    - minecraft
